Repository omnivore-app/omnivore, pull requests merged in 2022-03, with the labels that each got.

#244 use private bucket to upload page events
  packages/api/.env.test
  packages/api/src/datalayer/pubsub.ts
  packages/api/src/elastic/index.ts
  packages/api/src/resolvers/article/index.ts
  packages/api/src/routers/svc/pages.ts
  packages/api/src/util.ts
  packages/api/src/utils/uploads.ts
  packages/api/test/elastic/index.test.ts
  packages/api/test/resolvers/article.test.ts
  packages/api/test/resolvers/highlight.test.ts
Labels: API

#245 add Newsletter label to the page created by newsletters email
  packages/api/src/datalayer/pubsub.ts
  packages/api/src/elastic/index.ts
  packages/api/src/elastic/types.ts
  packages/api/src/resolvers/article/index.ts
  packages/api/src/resolvers/labels/index.ts
  packages/api/src/resolvers/links/index.ts
  packages/api/src/resolvers/save/index.ts
  packages/api/src/routers/svc/content.ts
  packages/api/src/routers/svc/pdf_attachments.ts
  packages/api/src/services/labels.ts
  packages/api/src/services/save_email.ts
  packages/api/src/services/save_file.ts
  packages/api/src/services/save_newsletter_email.ts
  packages/api/src/services/save_page.ts
  packages/api/test/elastic/index.test.ts
  packages/api/test/resolvers/article.test.ts
  packages/api/test/resolvers/highlight.test.ts
  packages/api/test/services/save_email.test.ts
  packages/api/test/services/save_newsletter_email.test.ts
  packages/api/test/util.ts
Labels: API, Newsletters

#256 Fix/newsletter label not add
  packages/api/src/elastic/index.ts
  packages/api/test/elastic/index.test.ts
  packages/api/test/services/save_newsletter_email.test.ts
Labels: Newsletters

#258 fix reading progress not updated after reading by updating cache
  packages/web/components/templates/homeFeed/HomeFeedContainer.tsx
  packages/web/lib/networking/queries/useGetLibraryItemsQuery.tsx
Labels: Web, Library

#266 Fix/city journal parsing
  packages/readabilityjs/Readability.js
  packages/readabilityjs/test/generate-testcase.js
  packages/readabilityjs/test/test-pages/city-journal/expected-metadata.json
  packages/readabilityjs/test/test-pages/city-journal/expected.html
  packages/readabilityjs/test/test-pages/city-journal/source.html
  packages/readabilityjs/test/test-pages/city-journal/url.txt
Labels: Parser

#271 [OMN-156] - Make header avatar less distracting
  packages/web/components/elements/Avatar.tsx
  packages/web/components/tokens/stitches.config.ts
Labels: GitStart, code/ready for review

#286 [OMN-189] : Settings View - Emails
  packages/web/components/elements/DropdownElements.tsx
  packages/web/components/elements/Tooltip.tsx
  packages/web/components/elements/images/MoreOptionsIcon.tsx
  packages/web/lib/networking/mutations/deleteNewsletterEmailMutation.ts
  packages/web/package.json
  packages/web/pages/_app.tsx
  packages/web/pages/settings/emails.tsx
  yarn.lock
Labels: GitStart, code/ready for review

#300 [Omn-192] - Settings View(Installation)
  packages/web/components/elements/DropdownElements.tsx
  packages/web/components/elements/ExtensionsInstallHelp.tsx
  packages/web/components/elements/MobileInstallHelp.tsx
  packages/web/components/elements/StyledText.tsx
  packages/web/components/elements/Tooltip.tsx
  packages/web/components/elements/images/ChromeIcon.tsx
  packages/web/components/elements/images/EdgeIcon.tsx
  packages/web/components/elements/images/FirefoxIcon.tsx
  packages/web/components/elements/images/InstallationIcon.tsx
  packages/web/components/elements/images/SafariIcon.tsx
  packages/web/components/elements/images/SaveArticleIcon.tsx
  packages/web/components/patterns/DropdownMenu.tsx
  packages/web/components/tokens/icons/AngleDownIcon.tsx
  packages/web/components/tokens/stitches.config.ts
  packages/web/pages/settings/installation/index.tsx
  packages/web/public/static/images/about/save-article-mobile.png
  packages/web/public/static/images/about/save-article.png
  packages/web/public/static/images/extension-preview.png
  packages/web/public/static/images/extension-preview@2x.png
  packages/web/public/static/images/mobile-app-preview.png
  packages/web/public/static/images/mobile-app-preview@2x.png
  packages/web/public/static/media/about/save-article-mobile.png
  packages/web/public/static/media/about/save-article.png
  packages/web/public/static/media/appStoreBadge.png
Labels: GitStart, code/ready for review

#344 Allow video playback on iOS
  apple/OmnivoreKit/Sources/Views/Article/WebAppView.swift
Labels: API, iOS, Reader
