Repository omnivore-app/omnivore, pull requests merged in 2022-07, with the labels that each got.

#807 [OMN-715]: Add a command pallet to the web
  packages/web/components/elements/KBar.tsx
  packages/web/components/patterns/HighlightBar.tsx
  packages/web/components/patterns/PrimaryHeader.tsx
  packages/web/components/templates/article/ArticleActionsMenu.tsx
  packages/web/components/templates/homeFeed/HomeFeedContainer.tsx
  packages/web/lib/hooks/useReaderSettings.tsx
  packages/web/lib/keyboardShortcuts/navigationShortcuts.ts
  packages/web/lib/keyboardShortcuts/useKeyboardShortcuts.ts
  packages/web/lib/networking/queries/search.tsx
  packages/web/package.json
  packages/web/pages/[username]/[slug]/index.tsx
  packages/web/pages/_app.tsx
  yarn.lock
Labels: GitStart, code/ready for review

#976 #895 - Improve table used on the /settings/api page
  packages/api/src/routers/auth/auth_router.ts
  packages/web/components/elements/Button.tsx
  packages/web/components/elements/ModalPrimitives.tsx
  packages/web/components/elements/Table.tsx
  packages/web/components/templates/EmailLogin.tsx
  packages/web/package.json
  packages/web/pages/settings/api.tsx
Labels: PR ready

#989 email-login, email-signup, confirm-email and reset-password router
  packages/api/.env.example
  packages/api/.nycrc
  packages/api/package.json
  packages/api/src/apollo.ts
  packages/api/src/datalayer/user/model.ts
  packages/api/src/entity/user.ts
  packages/api/src/events/reports/content_display_report_created.ts
  packages/api/src/events/user/user_created.ts
  packages/api/src/generated/graphql.ts
  packages/api/src/generated/schema.graphql
  packages/api/src/resolvers/function_resolvers.ts
  packages/api/src/resolvers/send_install_instructions/index.ts
  packages/api/src/resolvers/user/index.ts
  packages/api/src/routers/auth/auth_router.ts
  packages/api/src/routers/auth/mobile/account_creation.ts
  packages/api/src/routers/svc/emails.ts
  packages/api/src/routers/svc/reminders.ts
  packages/api/src/schema.ts
  packages/api/src/services/create_user.ts
  packages/api/src/services/send_emails.ts
  packages/api/src/util.ts
  packages/api/src/utils/auth.ts
  packages/api/src/utils/helpers.ts
  packages/api/src/utils/sendEmail.ts
  packages/api/test/db.ts
  packages/api/test/resolvers/article_saving_request.test.ts
  packages/api/test/resolvers/user.test.ts
  packages/api/test/routers/article.test.ts
  packages/api/test/routers/auth.test.ts
  packages/api/test/routers/reminders.test.ts
  packages/api/test/services/create_user.test.ts
  packages/db/migrations/0088.do.add_status_to_user.sql
  packages/db/migrations/0088.undo.add_status_to_user.sql
  packages/db/migrations/0089.do.drop_membership_from_user.sql
  packages/db/migrations/0089.undo.drop_membership_from_user.sql
  yarn.lock
Labels: API
